期末项目/django-blog-master/blog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from blog.views import IndexView, BlogDetailView, TagView, ArchiveView, LinkView, SearchView
from blog.views import ArticleAddView
from blog.views import bad_request, page_not_found, permission_denied

# 定义错误跳转页面
handler400 = bad_request
handler403 = permission_denied
handler404 = page_not_found
handler500 = bad_request

app_name = 'blog'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    # 某篇文章的详细信息
    url(r"^post/view/(?P<slug>[\w,-]+)", BlogDetailView.as_view(), name="detail"),
    # 新建文章
    url(r"^post/add/$", ArticleAddView.as_view(), name="add"),
    # 修改文章
    url(r"^post/edit/(?P<pk>\d+)", BlogDetailView.as_view(), name="edit"),
    # 标签信息
    url(r'^tag/$', TagView.as_view(), name="tags"),
    # 某个标签信息
    url(r'^tag/(?P<tag>\w+)', TagView.as_view(), name="tag-detail"),
    # 归档信息
    url(r'^archive/$', ArchiveView.as_view(), name="archive"),
    # 友链信息
    url(r'^link/', LinkView.as_view(), name="link"),
    # 搜索内容
    url(r'^search', SearchView.as_view(), name="search"),
]

期末项目/django-blog-master/djangoBlog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

APPEND_SLASH = True
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    # 博客url
    url(r'', include('blog.urls')),
    # 相册url
    url(r'^photo/', include('photo.urls')),
    # 编辑器url
    url(r'mdeditor/', include('mdeditor.urls')),
    url(r'^comments/', include('django_comments.urls')),
]

# 配置上传文件的目录
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

期末项目/django-blog-master/photo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from photo.views import PhotoGroupView, PhotoView, UploadView

app_name = 'photo'
urlpatterns = [
    url(r'^$', PhotoGroupView.as_view(), name="photogroup"),
    # 显示图片列表0
    url(r'^photo/(?P<group>\w+)/$', PhotoView.as_view(), name="photo"),
    # 上传图片
    url(r'^upload/$', UploadView.as_view(), name="upload"),
]

期末项目/django-blog-master/photo/models.py
# -*- coding: utf-8 -*-

from django.db import models
from blog.storage import PathAndRename
from django.utils.html import format_html


class PhotoGroup(models.Model):
    name = models.CharField(u'标题', max_length=150, unique=True)
    cover = models.ImageField(upload_to=PathAndRename("photocover"), verbose_name=u'封面')
    desc = models.TextField(u'描述', )
    create_time = models.DateTimeField(u'创建时间', auto_now_add=True)
    update_time = models.DateTimeField(u'更新时间', auto_now=True)
    active = models.BooleanField(u'开启', default=True)

    class Meta:
        verbose_name = u'相册'
        verbose_name_plural = u'相册'

    def __str__(self):
        return self.name


class Photo(models.Model):
    photo = models.ImageField(upload_to=PathAndRename("photo"), verbose_name=u'照片')
    desc = models.TextField(null=True, blank=True, verbose_name=u'描述')
    group = models.ForeignKey('PhotoGroup', on_delete=models.CASCADE, blank=True)
    create_time = models.DateTimeField(u'创建时间', auto_now_add=True)
    update_time = models.DateTimeField(u'更新时间', auto_now=True)

    class Meta:
        verbose_name = u'照片'
        verbose_name_plural = u'照片'

    def view_img(self):
        return format_html("<img src='/upload/%s' height='200'/>" % self.photo)

    view_img.short_description = '预览'
    view_img.allow_tags = True

期末项目/django-blog-master/photo/views.py
# -*- coding: utf-8 -*-

import os
import datetime
import json

from django.views.generic import ListView, View
from photo.models import Photo, PhotoGroup
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.conf import settings
from django.http import HttpResponse


class PhotoGroupView(ListView):
    """
    首页
    """
    template_name = 'photogroup.html'
    context_object_name = "photogroups"
    queryset = PhotoGroup.objects.filter(active=True)

    def get_context_data(self, **kwargs):
        context = super(PhotoGroupView, self).get_context_data(**kwargs)
        return context


class PhotoView(ListView):
    """
    首页
    """
    template_name = 'photo.html'
    context_object_name = "photos"
    queryset = Photo.objects.all()

    def get_queryset(self):
        group = self.kwargs.get('group')
        context = super(PhotoView, self).get_queryset().filter(group__name=group)
        return context

    def get_context_data(self, **kwargs):
        context = super(PhotoView, self).get_context_data(**kwargs)

        group = self.kwargs.get('group')
        group_id = PhotoGroup.objects.get(name=group).id

        prev_post = None
        next_post = None

        try:
            prev_post = PhotoGroup.objects.get(active=True, pk=(group_id - 1))
        except Exception as e:
            print(e)

        try:
            next_post = PhotoGroup.objects.get(active=True, pk=(group_id + 1))
        except Exception as e:
            print(e)

        context['prev_post'] = prev_post
        context['next_post'] = next_post
        return context


class UploadView(View):
    """ upload image file """

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(UploadView, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        upload_image = request.FILES.get("image-file", None)
        upload_dir = 'post'
        media_root = settings.MEDIA_ROOT

        # image none check
        if not upload_image:
            return HttpResponse(json.dumps({
                'success': 0,
                'message': "未获取到要上传的图片",
                'url': ""
            }))

        # image format check
        file_name_list = upload_image.name.split('.')
        file_extension = file_name_list.pop(-1)
        file_name = '.'.join(file_name_list)

        # image floder check
        file_path = os.path.join(media_root, upload_dir)
        if not os.path.exists(file_path):
            try:
                os.makedirs(file_path)
            except Exception as err:
                return HttpResponse(json.dumps({
                    'success': 0,
                    'message': "上传失败：%s" % str(err),
                    'url': ""
                }))

        # save image
        file_full_name = '%s_%s.%s' % (file_name,
                                       '{0:%Y%m%d%H%M%S%f}'.format(datetime.datetime.now()),
                                       file_extension)
        with open(os.path.join(file_path, file_full_name), 'wb+') as file:
            for chunk in upload_image.chunks():
                file.write(chunk)

        return HttpResponse(json.dumps({'success': 1,
                                        'message': "上传成功！",
                                        'url': os.path.join(settings.MEDIA_URL, upload_dir, file_full_name)}))

期末项目/django-blog-master/templates/archive.html
{% extends "layout/base.html" %}

{% block title %}
| 归档
{% endblock %}

{% block content %}
<div id="main" class="content">
    <div class="container">
        <section class="post_content" itemscope itemtype="http://schema.org/Article">
            <header class="post_header">
                <h1 class="post_title">归档</h1>
            </header>
            <div class="post-Archive">
                <div id="archives">
                    {% regroup archive_posts by publish_time.year as posts_by_year %}
                    <div class='archive-title'>
                        {% for year in posts_by_year %}
                        <h2 text="{{ year.grouper }}"></h2>
                            {% regroup year.list by publish_time.month as posts_by_month %}
                                {% for month in posts_by_month %}
                                    <h3>{{ month.grouper }}月 ({{month.list | length}})</h3>
                                    {% for post in month.list %}
                                        <div class='archives'>
                                            <div class="brick">
                                                <a href="{{ post.get_absolute_url }}">
                                                    <span class="time">{{ post.publish_time |date:'m-d h:m' }}</span>
                                                    {{ post.name }}
                                                </a>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}

期末项目/django-blog-master/templates/article_add.html
{% extends "layout/base.html" %}

{% block title %}
| 新建文章
{% endblock %}

{% block content %}
<div id="main" class="content">
    <div class="container">
        <section class="post_content post_add">
            <header class="post_header">
                <h1 class="post_title">新建文章</h1>
            </header>
            <div class="publish center-block">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">发 布</button>
                </form>
            </div>
        </section>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    document.onpaste = function (event) {
        var items = (event.clipboardData || event.originalEvent.clipboardData).items;
        //console.log(JSON.stringify(items)); // will give you the mime types
        for (var index in items) {
            var item = items[index];
            if (item.kind === 'file') {
                var blob = item.getAsFile();
                console.log(blob)
                //ajax上传图片
                $.post("{:url('/photo/upload/')}", {base: blob}, function (ret) {
                    if (ret.code === 1) {
                        //新一行的图片显示
                        MarkDownEditor.insertValue("\n![" + ret.data.title + "](" + ret.data.path + ")");
                    }
                });
            }
        }
    }
</script>
{% endblock %}

期末项目/django-blog-master/templates/detail.html
{% extends "layout/base.html" %}
{% block title %}
| {{ post.name }}
{% endblock %}

{% block content %}
<div id="main" class="content">
    <div class="container">
        <section class="post_content">
            <header class="post_header">
                <h1 class="post_title">{{ post.name }}
                    {% if user.is_staff %}
                    <a href="/admin/blog/article/{{ post.id }}/change/"><img src="/statics/images/svg/edit.svg"
                                                                             width="20" height="20"></a>
                    <!--<a href="/post/edit/{{ post.id }}"><img src="/statics/images/svg/edit.svg" width="20" height="20"></a>-->
                    {% endif %}
                </h1>
            </header>
            <div class="post-body">
                {% autoescape off %}
                {{ post.content }}
                {% endautoescape %}
            </div>
            <hr/>
            <div class="meta split split--responsive cf">
                <div class="split__title">
                    <time>{{ post.publish_time|date:'Y-m-d' }} |</time>
                    {% for tag in post.tags.all %}
                    <a href="/tag/{{tag.name}}" class="tag">{{tag.name}}</a>
                    {% empty %}
                    <a class="tag">未设置标签</a>
                    {% endfor %}
                </div>
                <div class="slide">
                    <a class="btn-slide" title="switch down"><img src="/statics/images/svg/comment.svg">折叠评论区</a>
                </div>
            </div>
        </section>
    </div>

    <div id="panel">
        <div class="comment-area">
            <section class="comments">
                <div class="comments-main">
                    <div class="comments-list">
                        <a class="comments-list-title"><span>30</span> 条评论</a>
                        <ul class="commentwrap">
                            <li class="comment even thread-even depth-1" id="li-comment-">
                                <div class="comment_body contents">
                                    <div class="profile">
                                        <a href=""><img src="/statics/images/favicon.png"
                                                        class="gravatar" alt="路飞"></a>
                                    </div>
                                    <div class="main shadow">
                                        <div class="commentinfo">
                                            <section class="commeta">
                                                <div class="shang">
                                                    <h4 class="author"><a href="" target="_blank"><img
                                                            src="/statics/images/favicon.png"
                                                            class="gravatarsmall" alt="路飞">路飞</a></h4>
                                                </div>
                                            </section>
                                        </div>
                                        <p>挺好的</p>
                                        <div class="xia info">
                                            <span><time datetime="2023-5-31">2023年5月31日</time></span>
                                            <span><a rel='nofollow' class='comment-reply-link'
                                                     onclick='return addComment.moveForm( "comment-969", "969", "respond", "1202" )'
                                                     aria-label='回复给路飞'>回复</a></span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <!-- #comment-## -->
                        </ul>
                    </div>

                    <div id="respond" class="comment-respond">
                        <h6 id="replytitle" class="comment-reply-title"><a rel="nofollow" id="cancel-comment-reply-link"
                                                                           href="" style="display:none;">取消</a></h6>
                        <form action="#" method="post" id="commentform" class="clearfix">
                            <div class="clearfix"></div>
                            <div class="author-info">
                                <input type="text" name="author" id="author" placeholder="昵  称 : " value="" tabindex="1"
                                       title="Name (required)"/>
                                <input type="text" name="email" id="email" placeholder="邮  箱 : " value="" tabindex="2"
                                       title="E-mail(will not be published) required"/>
                                <input type="text" name="url" id="url" placeholder="网  址 : " value="" tabindex="3"
                                       title="Website"/>
                            </div>
                            <div class="clearfix"></div>
                            <input type='hidden' name='comment_post_ID' value='1202' id='comment_post_ID'/>
                            <input type='hidden' name='comment_parent' id='comment_parent' value='0'/>
                            <p style="display: none;"><input type="hidden" id="akismet_comment_nonce"
                                                             name="akismet_comment_nonce" value="632104fca1"/></p>
                            <p style="display: none;"><input type="hidden" id="ak_js" name="ak_js" value="87"/></p>
                            <div class="comment-form-info">
                                <div class="real-time-gravatar"><img id="real-time-gravatar"
                                                                     src="/statics/images/favicon.png"
                                                                     alt="gravatar头像"/>
                                </div>
                                <p class="input-row">
                                    <i class="row-icon"></i>
                                    <textarea class="text_area" rows="3" cols="80" name="comment" id="comment"
                                              tabindex="4" placeholder="你不说两句吗？(°∀°)"></textarea>
                                    <input type="submit" name="submit" class="button" id="submit" tabindex="5"
                                           value="发送"/>
                                </p>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

<div class="navpost-part">
    <div id="NextPrevPosts">
        <div class="prev" data-aos="slide-right" data-aos-delay="1.5s">
            <div class="arrow"><img src="/statics/images/svg/left.svg"></div>
            <div class="preview">
                {% if prev_post %}
                {% if prev_post.cover %}
                <div class="pull-left featuredImg" style="background-image:url(/upload/{{ prev_post.cover }});"></div>
                {% else %}
                <div class="pull-left featuredImg" style="background-image:url('/statics/images/empty.png');"></div>
                {% endif %}
                <a class="pull-left preview-content bold" href="{{ prev_post.get_absolute_url }}"><span>{{ prev_post.name }}</span></a>
                {% else %}
                <div class="pull-left featuredImg" style="background-image:url('/statics/images/empty.png');"></div>
                <a class="pull-left preview-content bold" href="#"><span>拜托！泥垢了</span></a>
                {% endif %}
            </div>
        </div>
        <div class="next" data-aos="slide-left" data-aos-delay="1.5s">
            <div class="arrow"><img src="/statics/images/svg/right.svg"></div>
            <div class="preview">
                {% if next_post %}
                {% if next_post.cover %}
                <div class="pull-right featuredImg" style="background-image:url(/upload/{{ next_post.cover }});"></div>
                {% else %}
                <div class="pull-right featuredImg" style="background-image:url('/statics/images/empty.png');"></div>
                {% endif %}
                <a class="pull-right preview-content bold" href="{{ next_post.get_absolute_url }}"><span>{{ next_post.name }}</span></a>
                {% else %}
                <div class="pull-right featuredImg" style="background-image:url('/statics/images/empty.png');"></div>
                <a class="pull-right preview-content bold" href="#"><span>哼！我也是有底线的</span></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

期末项目/django-blog-master/templates/error.html
{% extends "layout/base.html" %}

{% block title %}
| {{code}}页面
{% endblock %}

{% block content %}
<div id="main" class="content">
    <div class="container">
        <section class="post_content">
            <header class="post_header">
                <h1 class="post_title">{{msg}}</h1>
            </header>
            <div class="links">
                <h3>这是{{code}}页面</h3>
                <h3>這是{{code}}頁面</h3>
                <h3>This is a {{code}} page</h3>
                <h3>Ceci est une page {{code}}</h3>
                <h3>これは{{code}}ページです</h3>
                <h3>Это {{code}} страница</h3>
                <h3>Esta es una página {{code}}</h3>
            </div>
        </section>
    </div>
</div>
{% endblock %}

期末项目/django-blog-master/templates/index.html
{% extends "layout/base.html" %}

{% block title %}
| 首页
{% endblock %}

{% block content %}

<div id="main" class="content">
    <div class="container">
        <article itemscope="itemscope">
            <div class="posts-list js-posts">
                {% if user.is_staff  %}
                <div class="post add-post">
                    <!--<a href="{% url 'blog:add' %}">-->
                    <a href="/admin/blog/article/add/">
                        <img src="/statics/images/svg/edit.svg" width="20" height="20">
                        来一篇新的文章
                    </a>
                </div>
                {% endif %}

                {% for post in posts %}
                    {% if post.type == 'l' %}
                        {% include './layout/l_post.html' %}
                    {% elif post.type == 'w' %}
                        {% include './layout/w_post.html' %}
                    {% else %}
                        {% include './layout/j_post.html' %}
                    {% endif %}
                {% empty %}
                    <div class="post no-post">暂时还没有发布的文章！</div>
                {% endfor %}
            </div>
            <!-- post-formats end Infinite Scroll star -->
            <!-- post-formats -->
            {% block pagination %}
                {% if is_paginated %}
                    {% include './layout/pagination.html' %}
                {% endif %}
            {% endblock %}
            <!-- -pagination  -->
        </article>
    </div>
</div>

{% endblock %}

期末项目/django-blog-master/templates/link.html
{% extends "layout/base.html" %}

{% block title %}
    | 友链
{% endblock %}

{% block content %}
    <div id="main" class="content">
        <div class="container">
            <section class="post_content">
                <header class="post_header">
                    <h1 class="post_title">链接</h1>
                </header>
                <div class="links">
                    <h3 class="catalog-title">Life Blog</h3>
                    <div class="catalog-description"></div>
                    <div class="catalog-share">4 items in collection</div>
                    <div class="userItems">
                        {% for post in posts %}
                            <div class="userItem">
                                <div class="userItem--inner">
                                    <div class="userItem-content">
                                        <img alt='' src="/upload/{{ post.cover }}" height='64' width='64'/>
                                        <div class="userItem-name">
                                            <a class="link link--primary" target="_blank">{{ post.name }}</a>
                                        </div>
                                        <a href="{{ post.link }}">{{ post.desc }}</a>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            <div class="userItem">
                                <div class="userItem--inner">
                                    <p>还没有添加友情链接</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </section>

        </div>
    </div>
{% endblock %}

期末项目/django-blog-master/templates/photo.html
{% extends "layout/base.html" %}

{% block title %}
| 相册
{% endblock %}

{% block content %}
<div id="main" class="content">
    <div class="container">
        <section class="post_content">
            <div class="photoItems">
                <div class="photo-content">
                    <div id="xxoo" class="chroma-gallery">
                        {% for photo in photos %}
                        <img src="/upload/{{photo.photo}}" alt="{{photo.desc}}" data-largesrc="/upload/{{photo.photo}}">
                        {% empty %}
                        <img src="/statics/images/thumbs/1.jpg" alt="大街" data-largesrc="/statics/images/thumbs/1.jpg">
                        <img src="/statics/images/thumbs/2.jpg" alt="长河" data-largesrc="/statics/images/thumbs/2.jpg">
                        <img src="/statics/images/thumbs/3.jpg" alt="小玩意" data-largesrc="/statics/images/thumbs/3.jpg">
                        <img src="/statics/images/thumbs/4.jpg" alt="猫头鹰" data-largesrc="/statics/images/thumbs/4.jpg">
                        <img src="/statics/images/thumbs/5.jpg" alt="高楼" data-largesrc="/statics/images/thumbs/5.jpg">
                        <img src="/statics/images/thumbs/6.jpg" alt="老街" data-largesrc="/statics/images/thumbs/6.jpg">
                        <img src="/statics/images/thumbs/7.jpg" alt="狗王" data-largesrc="/statics/images/thumbs/7.jpg">
                        <img src="/statics/images/thumbs/8.jpg" alt="现代化大厦" data-largesrc="/statics/images/thumbs/8.jpg">
                        <img src="/statics/images/thumbs/9.jpg" alt="豹子" data-largesrc="/statics/images/thumbs/9.jpg">
                        <img src="/statics/images/thumbs/10.jpg" alt="日光瀑布" data-largesrc="/statics/images/thumbs/10.jpg">
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div class="navpost-part">
        <div id="NextPrevPosts">
            <div class="prev" data-aos="slide-right" data-aos-delay="1.5s">
                <div class="arrow"><img src="/statics/images/svg/left.svg"></div>
                <div class="preview">
                    {% if prev_post %}
                    {% if prev_post.cover %}
                    <div class="pull-left featuredImg"
                         style="background-image:url(/upload/{{ prev_post.cover }});"></div>
                    {% else %}
                    <div class="pull-left featuredImg" style="background-image:url('/statics/images/empty.png');"></div>
                    {% endif %}
                    <a class="pull-left preview-content bold" href="/photo/photo/{{ prev_post.name }}/"><span>{{ prev_post.name }}</span></a>
                    {% else %}
                    <div class="pull-left featuredImg" style="background-image:url('/statics/images/empty.png');"></div>
                    <a class="pull-left preview-content bold" href="#"><span>海底月是天上月</span></a>
                    {% endif %}
                </div>
            </div>
            <div class="next" data-aos="slide-left" data-aos-delay="1.5s">
                <div class="arrow"><img src="/statics/images/svg/right.svg"></div>
                <div class="preview">
                    {% if next_post %}
                    {% if next_post.cover %}
                    <div class="pull-right featuredImg"
                         style="background-image:url(/upload/{{ next_post.cover }});"></div>
                    {% else %}
                    <div class="pull-right featuredImg"
                         style="background-image:url('/statics/images/empty.png');"></div>
                    {% endif %}
                    <a class="pull-right preview-content bold" href="/photo/photo/{{ next_post.name }}/"><span>{{ next_post.name }}</span></a>
                    {% else %}
                    <div class="pull-right featuredImg"
                         style="background-image:url('/statics/images/empty.png');"></div>
                    <a class="pull-right preview-content bold" href="#"><span>我也是有底线的</span></a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

期末项目/django-blog-master/templates/photogroup.html
{% extends "layout/base.html" %}

{% block title %}
| 相册
{% endblock %}

{% block content %}
<div id="main" class="content">
    <div class="container">
        <section class="post_content">
            <header class="post_header">
                <h1 class="post_title">相册</h1>
            </header>
            <div class="photoItems">
                <ul id="da-thumbs" class="da-thumbs">
                    {% for photogroup in photogroups %}
                    <li>
                        <a href="/photo/photo/{{ photogroup.name }}/" class="b-link-stripe b-animate-go thickbox">
                            <img src="/upload/{{ photogroup.cover }}" width="250" height="250" alt=""/>
                            <div>
                                <h5>{{ photogroup.name }}</h5>
                                <span>{{ photogroup.desc }}</span>
                            </div>
                        </a>
                    </li>
                    {% empty %}
                        <div>
                            <h5>快去建立相册吧！</h5>
                            <span>相册都没有，图片肯定没有！</span>
                        </div>
                    {% endfor %}
                </ul>
            </div>
        </section>
    </div>
</div>
{% endblock %}

期末项目/django-blog-master/templates/search.html
{% extends "layout/base.html" %}

{% block title %}
| 搜索
{% endblock %}

{% block content %}
<div id="main" class="content">
    <div class="container">
        <section class="post_content">
            <header class="post_header">
                <h1 class="post_title">搜索 <span>"{{request.GET.search}}"</span></h1>
            </header>
            <div class="posts-list js-posts">
                {% for post in search_posts %}
                    {% include './layout/s_post.html' %}
                {% empty %}
                    <div class="no-post">想要我的财宝吗？去找吧！</div>
                {% endfor %}
            </div>
            <!-- post-formats end Infinite Scroll star -->
            <!-- post-formats -->
            {% block pagination %}
                {% if is_paginated %}
                    {% include './layout/pagination.html' %}
                {% endif %}
            {% endblock %}
            <!-- -pagination  -->
            </article>
        </section>
    </div>
</div>
{% endblock %}