期末项目/django-blog-master/blog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from blog.views import IndexView, BlogDetailView, TagView, ArchiveView, LinkView, SearchView
from blog.views import ArticleAddView
from blog.views import bad_request, page_not_found, permission_denied

# 定义错误跳转页面
handler400 = bad_request
handler403 = permission_denied
handler404 = page_not_found
handler500 = bad_request

app_name = 'blog'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    # 某篇文章的详细信息
    url(r"^post/view/(?P<slug>[\w,-]+)", BlogDetailView.as_view(), name="detail"),
    # 新建文章
    url(r"^post/add/$", ArticleAddView.as_view(), name="add"),
    # 修改文章
    url(r"^post/edit/(?P<pk>\d+)", BlogDetailView.as_view(), name="edit"),
    # 标签信息
    url(r'^tag/$', TagView.as_view(), name="tags"),
    # 某个标签信息
    url(r'^tag/(?P<tag>\w+)', TagView.as_view(), name="tag-detail"),
    # 归档信息
    url(r'^archive/$', ArchiveView.as_view(), name="archive"),
    # 友链信息
    url(r'^link/', LinkView.as_view(), name="link"),
    # 搜索内容
    url(r'^search', SearchView.as_view(), name="search"),
]

期末项目/django-blog-master/djangoBlog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

APPEND_SLASH = True
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    # 博客url
    url(r'', include('blog.urls')),
    # 相册url
    url(r'^photo/', include('photo.urls')),
    # 编辑器url
    url(r'mdeditor/', include('mdeditor.urls')),
    url(r'^comments/', include('django_comments.urls')),
]

# 配置上传文件的目录
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

期末项目/django-blog-master/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" href="/statics/images/favicon.png">
    <title>
        A Blog
        {% block title %}
        {% endblock %}
    </title>
    <meta name="description" content="itimor django blog python"/>
    <meta name="keywords" content="itimor django blog python"/>
    <link href="/statics/css/base.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/statics/css/index.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/statics/css/highlight.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/statics/css/jquery.backTotop.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/statics/css/lightbox.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/statics/css/hoverdir.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/statics/css/chromagallery.min.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/statics/css/comment.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/statics/css/mobile.css" rel="stylesheet" type="text/css" media="all"/>
</head>

{% block extra_head %}
{% endblock %}
<body>
<div id="particles-js"></div>
{% block header %}
    {% include 'layout/header.html' %}
{% endblock %}

{% block content %}
{% endblock %}

{% block extScriptFile %}
{% endblock %}

{% block footer %}
    {% include 'layout/footer.html' %}
{% endblock %}
</body>
</html>

期末项目/django-blog-master/templates/layout/footer.html
<footer id="footer" class="overlay animated from-top">
    <div class="row footer-info">
        <div></div>
        <div class="socialize">
            {% for social in social_list %}
            <li class="tooltip">
                <a title="{{social.name}}" class="socialicon" href="{{social.url}}">
                    <img alt="{{social.name}}" src="/upload/{{social.cover}}">
                </a>
                <div class="tooltip-social">{{social.name}}</div>
            </li>
            {% empty %}
            <li>
                <a title="weibo" class="socialicon" href="https://weibo.com/u/2646775602">
                    <img src="/statics/images/svg/weibo.svg">
                </a>
            </li>
            <li>
                <a title="github" class="socialicon" href="https://github.com/itimor">
                    <img src="/statics/images/svg/github.svg">
                </a>
            </li>
            <li>
                <a title="jianshu" class="socialicon" href="https://www.jianshu.com/u/40758c9db703">
                    <img src="/statics/images/svg/jianshu.svg">
                </a>
            </li>
            {% endfor %}
        </div>
        <div></div>
    </div>
    <div class="cr">
        Copyright&copy;<a href="https://github.com/itimor">Itimor</a>
        Power by <a href="https://www.djangoproject.com/">Django</a>
    </div>
    <script type='text/javascript' src='/statics/js/jquery.min.js'></script>
    <script type='text/javascript' src='/statics/js/plugins.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script src="//cdn.bootcss.com/highlightjs-line-numbers.js/1.1.0/highlightjs-line-numbers.min.js"></script>
    <script type='text/javascript' src='/statics/js/particles.js'></script>
    <script type='text/javascript' src='/statics/js/aos.js'></script>
    <script type='text/javascript' src='/statics/js/jquery.backTotop.js'></script>
    <script type='text/javascript' src='/statics/js/lightbox.js'></script>
    <script type='text/javascript' src='/statics/js/modernizr.js'></script>
    <script type='text/javascript' src='/statics/js/jquery.hoverdir.js'></script>
    <script type='text/javascript' src='/statics/js/chromagallery.min.js'></script>

    <script type='text/javascript' src='/statics/js/script.js'></script>
</footer>

期末项目/django-blog-master/templates/layout/header.html
<header id="masthead" class="overlay animated from-bottom" itemprop="brand">
    <form class="js-search search-form search-form--modal" method="get" action="{% url 'blog:search' %}" role="search">
        <div class="search-form__inner">
            <div>
                <div id="search-container" class="ajax_search">
                    <form method="get" id="searchform" action="{% url 'blog:search' %}">
                        <div class="filter_container">
                            <input type="text" value="" autocomplete="off" placeholder="search ..." name="search"/>
                            <ul id="search_filtered" class="search_filtered"></ul>
                        </div>
                        <input type="submit" id="searchsubmit" class="searchsubmit" value=""/>
                    </form>
                </div>
            </div>
        </div>
    </form>
    <div class="navi" data-aos="fade-down">
        <div class="bt-nav">
            <div class="line line1"></div>
            <div class="line line2"></div>
            <div class="line line3"></div>
        </div>
        <div class="navbar animated fadeInRight">
            <div class="inner">
                <nav id="site-navigation" class="main-navigation">
                    <div id="main-menu" class="main-menu-container">
                        <div class="menu-menu-container">
                            <ul id="primary-menu" class="menu">
                                <li class="menu-item active">
                                    <a href="/">首页</a>
                                </li>
                                <li class="menu-item">
                                    <a href="/tag/">标签</a>
                                </li>
                                <li class="menu-item">
                                    <a href="/archive/">归档</a>
                                </li>
                                <li class="menu-item">
                                    <a href="/photo/">相册</a>
                                </li>
                                <li class="menu-item">
                                    <a href="/link/">友链</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- #site-navigation -->
            </div>
        </div>
    </div>
    <div class="hebin" data-aos="fade-down">
        <a class=" js-toggle-search"><img src="/statics/images/svg/search.svg"></a>
    </div>
    <div class="site-branding text-center">
        {% if user.is_staff %}
            <a href="/logout">
                <figure>
                    <img class="custom-logo avatar" src="/statics/images/favicon.jpg"/>
                </figure>
            </a>
            <p style="color: #000;">This is my world</p>
        {% else %}
            <a href="/login">
                <figure>
                    <img class="custom-logo avatar" src="/statics/images/favicon.jpg"/>
                </figure>
            </a>
            <p>This is my world</p>
        {% endif %}

    </div>
    <!-- .site-branding -->

</header>

期末项目/django-blog-master/templates/layout/j_post.html
<div class="post post-layout-list" data-aos="fade-up">
    <div class="postnormal review">
        {% if post.cover %}
            <div class="status_user" style="background-image: url(/upload/{{ post.cover }});">
        {% else %}
            <div class="status_user" style="background-image: url(/statics/images/j_post.jpg);">
        {% endif %}
            <div class="status_section">
                <a href="{{ post.get_absolute_url }}" class="status_btn">{{ post.name }}</a>
{#                <div class="entry-content">#}
{#                {% autoescape off %}#}
{#                    {{ post.excerpt }}#}
{#                {% endautoescape %}#}
{#                </div>#}
            </div>
        </div>
    </div>
</div>

期末项目/django-blog-master/templates/layout/l_post.html
<div class="post post-layout-list" data-aos="fade-up">
    <div class="postnormal review">
        <div class="post-container review-item">
            <div class="row review-item-wrapper">
                <div class="col-sm-3">
                    <a rel="nofollow" href="{{ post.get_absolute_url }}">
                        {% if post.cover %}
                            <div class="review-item-img" style="background-image: url(/upload/{{ post.cover }});"></div>
                        {% else %}
                            <div class="review-item-img" style="background-image: url(/statics/images/tmp/l.jpg);"></div>
                        {% endif %}
                    </a>
                </div>
                <div class="col-sm-9 flex-xs-middle">
                    <div class="review-item-title">
                        <a href="{{ post.get_absolute_url }}">{{ post.name }}
                            {% if post.is_top %}
                                <img src="/statics/images/svg/top.svg">
                            {% endif %}
                        </a>
                        {% if user.is_authenticated %}
                            <a href="/admin/blog/article/{{ post.id }}/change/"><img src="/statics/images/svg/edit.svg" width="20" height="20"></a>
                            <!--<a href="/post/edit/{{ post.id }}"><img src="/statics/images/svg/edit.svg" width="20" height="20"></a>-->
                        {% endif %}
                    </div>
                    <div class="review-item-creator"><b>发布日期：</b>{{ post.publish_time|date:'Y-m-d h:m' }}</div>
                    <span class="review-item-info"><b>总浏览量：</b>{{ post.views }}</span>
                </div>
            </div>
            <div class="review-bg-wrapper">
                {% if post.cover %}
                    <div class="bg-blur" style="background-image: url(/upload/{{ post.cover }});"></div>
                {% else %}
                    <div class="bg-blur" style="background-image: url(/statics/images/l_post.jpg);"></div>
                {% endif %}
            </div>
        </div>
        <div class="post-container">
{#            <div class="entry-content">#}
{#                {% autoescape off %}#}
{#                    {{ post.excerpt }}#}
{#                {% endautoescape %}#}
{#            </div>#}
            <div class="post-footer">
                <div class="review-item-tag"><img src="/statics/images/svg/tag.svg">
                    {% for tag in  post.tags.all %}
                        <a href="/tag/{{tag.slug}}" class="tag">{{tag.name}}</a>
                    {% empty %}
                        <a class="tag">未设置标签</a>
                    {% endfor %}
                </div>
                <a class="gaz-btn primary pull-right" href="{{ post.get_absolute_url }}">阅读更多</a>
            </div>
        </div>
    </div>
</div>

期末项目/django-blog-master/templates/layout/pagination.html
<div class="pagination">
        <ul>
            {% if first %}
                <li><a href="?page=1">1</a></li>
            {% endif %}

            {% if left %}

                {% if left_has_more %}
                    <li><span>...</span></li>
                {% endif %}

                {% for i in left %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endfor %}

            {% endif %}

            <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>

            {% if right %}

                {% for i in right %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endfor %}

                {% if right_has_more %}
                    <li><span>...</span></li>
                {% endif %}

            {% endif %}

            {% if last %}
                <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
            {% endif %}
        </ul>
</div>

期末项目/django-blog-master/templates/layout/s_post.html
<div class="post post-layout-list" data-aos="fade-up">
    <div class="postnormal review">
        <div class="search_post">
            <a href="{{ post.get_absolute_url }}" class="search_title">{{ post.name }}</a>
{#            <div class="entry-content">#}
{#                {% autoescape off %}#}
{#                    {{ post.excerpt }}#}
{#                {% endautoescape %}#}
{#            </div>#}
        </div>
    </div>
</div>

期末项目/django-blog-master/templates/layout/w_post.html
<div class="post post-layout-list js-gallery" data-aos="fade-up">
    <div class="post-album">
        <div class="row content">
            <div class="bg" style="background: linear-gradient(to right, rgba(0,0,0,0.58), white);"></div>
            <div class="contentext flex-xs-middle">
                <div class="album-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.name }}</a>
                </div>
                <h5 class="review-item-creator"><b>发布日期：</b>{{ post.publish_time }}</h5>
{#                <div class="entry-content">#}
{#                {% autoescape off %}#}
{#                    {{ post.excerpt }}#}
{#                {% endautoescape %}#}
{#                </div>#}
            </div>
            <div class="album-thumb-width flex-xs-middle">
                <div class="row album-thumb no-gutter">
                    <div class="col-xs-4"><img class="thumb" src="/statics/images/tmp/IMG_0150-250x250.jpg"/>
                    </div>
                    <div class="col-xs-4"><img class="thumb" src="/statics/images/tmp/IMG_0149-250x250.jpg"/>
                    </div>
                    <div class="col-xs-4"><img class="thumb" src="/statics/images/tmp/IMG_0146-250x250.jpg"/>
                    </div>
                    <div class="col-xs-4"><img class="thumb" src="/statics/images/tmp/IMG_0147-250x250.jpg"/>
                    </div>
                    <div class="col-xs-4"><img class="thumb" src="/statics/images/tmp/IMG_0148-250x250.jpg"/>
                    </div>
                    <div class="col-xs-4">
                        <a href="">5 pics</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>